// Runtime config via config.js (generated by entrypoint.sh from Railway env vars)
// Priority: window.__ENV__ (runtime) > import.meta.env (build-time) > fallback

interface RuntimeEnv {
  VITE_API_BASE_URL?: string;
  VITE_APP_NAME?: string;
  VITE_POS_BASE_URL?: string;
}

declare global {
  interface Window {
    __ENV__?: RuntimeEnv;
  }
}

function getRuntimeEnv(): RuntimeEnv {
  return window.__ENV__ ?? {};
}

export function getApiBaseUrl(): string {
  return getRuntimeEnv().VITE_API_BASE_URL || import.meta.env.VITE_API_BASE_URL || '/api';
}

export function getAppName(): string {
  return getRuntimeEnv().VITE_APP_NAME || import.meta.env.VITE_APP_NAME || 'Library System Admin';
}

export function getPosBaseUrl(): string {
  return getRuntimeEnv().VITE_POS_BASE_URL || import.meta.env.VITE_POS_BASE_URL || '';
}
